[db.alarmengine]
    driver = "mysql"
    master = "root:root@tcp(localhost:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
    slave = []
    connMaxLifeTime = 10
    maxIdleConns = 10
    maxOpenConns = 10

[web]
    addr = ":8080"
